CREATE TABLE PLAYER
        (
        id NUMBER(10) NOT NULL AUTO_INCREMENT,
        name VARCHAR2(50) NOT NULL,
        password VARCHAR(500) NOT NULL,
        PRIMARY KEY(id)
        );

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 3 INCREMENT BY 1;